import CashierTemplate from "@/components/cashierTemplate";
import CashierMenuList from "@/app/cashierMenuList";

export const metadata = {
    title: 'Transaksi | Ordering System',
    description: 'Generated by create next app'
}

type PropsLayout = {
    children: React.ReactNode
}

const RootLayout = ({children}: PropsLayout) => {
    return (
        <CashierTemplate title="Transaksi" id="transaksi" menuList={CashierMenuList}>
            {children}
        </CashierTemplate>
    )
}

export default RootLayout;
